### ISSUE TITLE
segfault with gcc 7.3

### ISSUE THREAD

**Issue by ekg** [rizkg/BooPHF#11]
I tried to run the test benchmark, and ran into a segfault:

```
-> % ./Bootest 100000000 4 -check -bench            
key file generated 
Construct a BooPHF with  100000000 elements  
for info, total work write each  : 1.000    total work inram from level -1991486788 : -1991486787.000  total work raw : 25.000 
[Building BooPHF]  100  %   elapsed:   0 min 4  sec   remaining:   0 min 0  sec[1]    2339 segmentation fault (core dumped)  ./Bootest 100000000 4 -check -bench
```

I've traced the segfault here:

```
#0  0x00005555555656f5 in void boomphf::mphf<unsigned long, boomphf::SingleHashFunctor<unsigned long> >::pthread_processLevel<bfile_iterator>(std::vector<unsigned long, std::allocator<unsigned long> >&, std::shared_ptr<bfile_iterator>, std::shared_ptr<bfile_iterator>, int) ()
#1  0x0000555555565a9d in void* boomphf::thread_processLevel<unsigned long, boomphf::SingleHashFunctor<unsigned long>, file_binary, bfile_iterator>(void*) ()
#2  0x00007ffff7bbd6db in start_thread (arg=0x7ffff50bd700) at pthread_create.c:463
#3  0x00007ffff6fa788f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

This is my gcc version:

```
-> % g++ --version
g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
```

Probably it's unrelated, but I also see a lot of warnings of this type:

```
BooPHF.h:1026:10: warning: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 2 has type ‘uint64_t {aka long unsigned int}’ [-Wformat=]
``

**Comment by rizkg** [comment]
Thanks for reporting this ! 
It turns out the usage of Bootest was updated at some point and not propagated in the Readme. You should now use bootest like this :

    ./Bootest 100000000 4 1.0 -check -bench

Usage is :

    ./Bootest <nelem> <nthreads> <gamma>  [options]

The extra argument is to specify the gamma value ( gamma = 1.0 --> slower but less memory required, higher values will be faster with more mermory usage). 
The Readme and proper Bootest error report have now been updated accordingly in bc7dfa01ea0211c21d7963b2603871dda40ce49d.
